# Generated by Django 4.2.7 on 2025-08-19 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('zone_kit', models.CharField(max_length=20, verbose_name='Zone de Kit')),
                ('nombre_bacs', models.IntegerField(verbose_name='Nombre de bacs restants')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livré'), ('flc', 'FLC envoyé'), ('cloture', 'Clôturé')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_creees', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alertes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='StockDebord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_debord',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='alertes.alerte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historique_alertes',
                'ordering': ['-date_modification'],
            },
        ),
    ]
