# Generated by Django 4.2.7 on 2025-08-23 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationTravee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occupation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Occupation Travée',
                'verbose_name_plural': 'Occupations Travées',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement_sm', models.CharField(max_length=20, verbose_name='Emplacement SM')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('nombre_bacs', models.IntegerField(verbose_name='Nombre de Bac')),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'entrée")),
                ('travee_debord', models.CharField(max_length=10, verbose_name='Travée débord')),
                ('code_condi', models.CharField(max_length=10, verbose_name='Code condi')),
                ('qt_piece_uc', models.IntegerField(verbose_name='Qt pièce/UC')),
                ('appro', models.CharField(max_length=50, verbose_name='Appro')),
                ('fournisseur', models.CharField(max_length=100, verbose_name='Fournisseur')),
                ('cmj', models.CharField(max_length=20, verbose_name='CMJ')),
                ('f', models.CharField(max_length=10, verbose_name='F')),
            ],
            options={
                'verbose_name': 'Référence',
                'verbose_name_plural': 'Références',
            },
        ),
        migrations.CreateModel(
            name='Travee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
                ('capacite', models.IntegerField()),
                ('references', models.ManyToManyField(through='stock_debord.OccupationTravee', to='stock_debord.reference')),
            ],
            options={
                'verbose_name': 'Travée',
                'verbose_name_plural': 'Travées',
            },
        ),
        migrations.AddField(
            model_name='occupationtravee',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_debord.reference'),
        ),
        migrations.AddField(
            model_name='occupationtravee',
            name='travee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_debord.travee'),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('nombre_bacs', models.IntegerField()),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilisateur', models.CharField(max_length=100)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_debord.reference')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='occupationtravee',
            unique_together={('travee', 'reference')},
        ),
    ]
