# Generated by Django 4.2.7 on 2025-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('consultant', 'Consultant (Opérateur / Cariste)'), ('gestionnaire', 'Gestionnaire de magasin'), ('admin', 'Administrateur')], default='consultant', max_length=20),
        ),
    ]
